### ISSUE TITLE
Stock commands error

### ISSUE THREAD

**Issue by MashedTuna** [Rdimo/GenBot#4]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:428:10)
    at ReadStream.open (internal/fs/streams.js:131:13)
    at new ReadStream (internal/fs/streams.js:119:10)
    at Object.createReadStream (fs.js:1919:10)
    at Object.module.exports.run (/home/runner/GenBot/commands/Generator/stock.js:5:19)
    at module.exports (/home/runner/GenBot/events/Message/message.js:44:19)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/runner/GenBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/GenBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/GenBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Xarkata10** [comment]
TypeError: Cannot read properties of undefined (reading '2')
    at Object.module.exports.run (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\commands\Generator\stock.js:5:48)
    at module.exports (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\events\Message\message.js:43:19)
    at Client.emit (node:events:520:28)
    at MessageCreateAction.handle (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\hari_\OneDrive\Работен плот\GenBot-main\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:520:28)

**Comment by Xarkata10** [comment]
This is my error
